# 线性回归

In [103]:
import numpy as np
x1=np.arange(1,11)
x0=np.ones(10)
x=np.vstack((x1,x0)).T
y=(np.arange(1,11)+np.random.random((1,10))*0.011).reshape(10,1)
print(x)
print(y)
sig=np.array([[1],[2]])
delta=0.001
def error(sig,x,y):
    a=x.dot(sig)-y
    a=(a*a).sum()
    return a**0.5
def gradient(sig,x,y):
    c=x.dot(sig)-y
    d=x*c
    return (d.sum(0)).reshape(2,1)
for i in range(10000):
    #print(gradient(sig,x,y))
    if (np.absolute(gradient(sig,x,y))<1e-6).all():
        break
    else:
        sig=sig-gradient(sig,x,y)*delta
print('sig is')
print(sig)
print('error is ')
print(error(sig,x,y))


A=(x1*x1).sum()
B=(x1*x0).sum()
C=(x0*x0).sum()
D=x1.dot(y)
E=x0.dot(y)
sig21=(C*D-B*E)/(A*C-B*B)
sig22=(B*D-A*E)/(B*B-A*C)
sig2=np.array([sig21,sig22])
print('直接求的sig')
print(sig2)
print('直接求的误差')
print(error(sig2,x,y))

[[ 1.  1.]
 [ 2.  1.]
 [ 3.  1.]
 [ 4.  1.]
 [ 5.  1.]
 [ 6.  1.]
 [ 7.  1.]
 [ 8.  1.]
 [ 9.  1.]
 [10.  1.]]
[[ 1.00333139]
 [ 2.00601494]
 [ 3.00239294]
 [ 4.00933241]
 [ 5.00454521]
 [ 6.00051581]
 [ 7.00214996]
 [ 8.00988969]
 [ 9.00777641]
 [10.00674523]]
sig is
[[1.00033303]
 [0.00343781]]
error is 
0.009088563965459196
直接求的sig
[[1.0003331 ]
 [0.00343734]]
直接求的误差
0.009088563938743164


# 逻辑回归

In [ ]:
from numpy import *
def loadDataSet():
    dataMat = []; labelMat = []  #训练数据集，标签List
    fr = open('testSet.txt')
    for line in fr.readlines():
        lineArr = line.strip().split()
        dataMat.append([1.0, float(lineArr[0]), float(lineArr[1])])  #分别是X0，X1，X2
        labelMat.append(int(lineArr[2]))  #标签
    return dataMat, labelMat
 def sigmoid(z):
    return 1.0/(1+exp(-z))
 def gradAscent(dataMatIn, classLabels):
    dataMatrix = mat(dataMatIn)             #100 * 3的矩阵
    labelMat = mat(classLabels).transpose() #100 * 1的列向量
    m, n = shape(dataMatrix)  #行数（样本数：100）、列数（特征数：3）
    alpha = 0.001  #目标移动的步长
    maxCycles = 500  #迭代次数
    weights = ones((n,1))  #初始回归系数。3*1的列向量，每个系数初始化为1.0。weights为numpy.matrix型
    for k in range(maxCycles):              #循环500次
        h = sigmoid(dataMatrix*weights)     #矩阵乘法：每个样本的特征值×系数，拔得出来的值作为sigmoid函数输入
        error = (labelMat - h)              #计算每个样本的sigmoid输出与标签的差值
        weights = weights + alpha * dataMatrix.transpose()* error 
        return weights
