# 创建数组

In [2]:
import numpy as np

## 直接输入 np.array

In [59]:
a=np.array([[1,2,3],[3,4,6]])
print(a)

[[1 2 3]
 [3 4 6]]


## 全为0，全为1，全为某一个值的数组 np.zeros & np.ones & np.full

In [4]:
a=np.zeros((3,5))
print('a:')
print(a)
b=np.ones((2,3))
print('b:')
print(b)
c=np.full((3,6),5)
print('c:')
print(c)

a:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
b:
[[1. 1. 1.]
 [1. 1. 1.]]
c:
[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


## 单位矩阵 np.eye

In [5]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 随机矩阵 np.random.random

In [6]:
a=np.random.random((3,4))
print(a)
# 建立0-1随机数

[[0.46850915 0.393105   0.23819346 0.15776807]
 [0.51882728 0.20123526 0.47877545 0.2101858 ]
 [0.46769071 0.08227767 0.47919179 0.21728782]]


## 建立均分数列 np.linspace & np.arange

建立均分数列，a=np.linspace(min,max,num=50，endpoint=True。。。)，默认均分成50份，默认包括最小和最大

建立均分数列2，a=np.arange(min=0,max,step=1) 默认包括最小，不包括最大，默认间距1，从min开始，一直加，直到超过max

In [7]:
a=np.linspace(1,10)
b=np.linspace(10,50,21)
c=np.arange(10)
d=np.arange(2,9,2)
print(a)
print(b)
print(c)
print(d)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48. 50.]
[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


# 数组维度

## 输出数组维度 np.shape

In [8]:
a=np.array([[1,2,3,4],[5,6,8,9]])
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 8 9]]
(2, 4)


## 更改数组维度 np.reshape

np.reshape 按照先行在列的顺序重新排列，不影响原数列值

In [9]:
a=np.arange(10)
print(a)
b=a.reshape(2,5)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


# 数组索引

数列索引中，行列数字是从0开始的，截取的范围包括小的，不包括大的

In [10]:
a=np.arange(12).reshape(3,4)
print(a)
print(a[1:3,2:4])
print(a[-2:,2:])
print(a[:,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 6  7]
 [10 11]]
[[ 6  7]
 [10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


# 数组计算

## 数组 + - 及数乘

数组+ - 直接对应位置元素相加，数乘直接所有元素乘以该数

In [21]:
a=np.arange(1,5).reshape((2,2))
b=np.ones((2,2))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*1.5)


[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[2. 3.]
 [4. 5.]]
[[0. 1.]
 [2. 3.]]
[[1.5 3. ]
 [4.5 6. ]]


数组+ - 要同维度，除非是行向量（/列向量），并且数量与对应矩阵的列数（/行数）相同，就挨个加过去

In [30]:
a=np.arange(1,9).reshape((2,4))
b=np.array([[1],[2]])
print(a)
print(b)
print(a+b)
print(a-b)
c=np.array([[1,2],[3,4]])
print(c)
print(a+c)


[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]]
[[ 2  3  4  5]
 [ 7  8  9 10]]
[[0 1 2 3]
 [3 4 5 6]]
[[1 2]
 [3 4]]


ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

## 数组 *乘

数组* 与+ -一样，对应元素乘，所以需要维度一样才行，除非是行向量（/列向量），并且数量与对应矩阵的列数（/行数）相同，就挨个乘过去

In [36]:
a=np.arange(1,9).reshape((2,4))
b=np.arange(1,9).reshape((2,4))
c=np.array([[1],[2]])
print(a)
print(b)
print(c)
print(a*b)
print(a*c)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[ 1  2  3  4]
 [10 12 14 16]]


## 数组 X乘 np.dot

数列A.dot(数列B)就是线性代数里的X乘

In [39]:
a=np.arange(1,4)
b=np.arange(6).reshape(3,2)
print(a)
print(b)
print(a.dot(b))

[1 2 3]
[[0 1]
 [2 3]
 [4 5]]
[16 22]


# 数列统计

## 求和 np.sum()

sum()可以求数列和，可以指定按某一维度来求和

In [52]:
a=np.arange(1,9).reshape((2,4))
print(a)
print(a.sum())
print(a.sum(0))
print(a.sum(1))

[[1 2 3 4]
 [5 6 7 8]]
36
[ 6  8 10 12]
[10 26]


## 求平均值 np.mean()

mean()可以求数列和，可以指定按某一维度来求和

In [60]:
a=np.arange(1,9).reshape((2,4))
print(a)
print(a.mean())
print(a.mean(0))
print(a.mean(1))

[[1 2 3 4]
 [5 6 7 8]]
4.5
[3. 4. 5. 6.]
[2.5 6.5]


## 求最大/最小值 np.max()/min()

max()/min()可以求最大值/最小值，可以指定按某一维度来求和

In [61]:
a=np.arange(1,9).reshape((2,4))
print(a)
print(a.max())
print(a.max(0))
print(a.min(1))

[[1 2 3 4]
 [5 6 7 8]]
8
[5 6 7 8]
[1 5]
